Fix EXISTS restriction
sraoss/pg_ivm pull request #71
Opened 2023-09-09 08:48 UTC by thoshiai

reinforce EXISTS restriction, only support the AND condition.

2023-09-11 06:33 UTC, yugo-n requested changes
This patch intends to fix a bug described in Issue #72.

However, this fix lacks recursive check, so still allow an expression including EXISTS under AND, like:

```
SELECT create_immv('mv_ivm_subquery', 'SELECT * FROM mv_base_a a WHERE true and CASE EXISTS(SELECT 1 FROM mv_base_b b WHERE a.i = b.i) WHEN true THEN false ELSE true END');
```

Also, the build fails on PostgreSQL 16.

2024-02-27 02:14 UTC, yugo-n requested changes
I think your fix is insufficient because the following query causes an error besides it should be Okay.

```
SELECT …. FROM tbl1 WEHRE tbl1. x > 10 AND EXISTS (SELECT 1 FROM tbl2 WHERE … )
```

Attached is a patch for fixing the problem on my idea (with another patch just for some code cleaning). These can be applied on the branch of this pull request.

[0001-Fix-check-for-EXISTS-subquery-support.patch.txt](https://github.com/sraoss/pg_ivm/files/14413398/0001-Fix-check-for-EXISTS-subquery-support.patch.txt)
[0002-Some-code-cleaning-and-comments-improvement.patch.txt](https://github.com/sraoss/pg_ivm/files/14413397/0002-Some-code-cleaning-and-comments-improvement.patch.txt)

My idea is adding a new boolean member allow_context into check_ivm_restriction_context. This member means whether EXISTS subquery is allowed **in the current node** being examined in check_ivm_restriction_walker. 

Currently, EXISTS subquery is allowed only directly under WHERE clause or in AND expression that is directly under WHERE, so this flag should be set to true just before calling check_ivm_restriction_walker for nodes directly under WHERE or operands of AND expression direct under WHERE. Also, to confirm that EXISTS is not allowed in other expression, this flag is reset to false on every call of the function.
   
In passing, I removed unnecessary members in check_ivm_restriction_context, and moved the check for OR and NOT expression  was moved from  rewrite_exists_subquery_walker to check_ivm_restriction_context. I would like to include these fixes if you don't mind.

2024-02-27 11:00 UTC, yugo-n commented
I copy and paste the patch here for making your review easer.

[0001-Fix-check-for-EXISTS-subquery-support.patch.txt](https://github.com/sraoss/pg_ivm/files/14413398/0001-Fix-check-for-EXISTS-subquery-support.patch.txt)
```diff
From 7e93cc1e176fbfda1d0cfe3bf4969988197dc680 Mon Sep 17 00:00:00 2001
From: Yugo Nagata <nagata@sraoss.co.jp>
Date: Tue, 27 Feb 2024 10:38:33 +0900
Subject: [PATCH 1/2] Fix check for EXISTS subquery support

Currently, EXISTS subquery is allowed only directly under WHERE
clause or in AND expression that is directly under WHERE.

In order to confirm this, I added a new boolean member
allow_context into check_ivm_restriction_context. This member
means whether EXISTS subquery is allowed in the current node being
examined in   check_ivm_restriction_walker. This should be set
just before calling check_ivm_restriction_walker for nodes directly
under WHERE or operands of AND expression direct under WHERE, and
is reset to false on every call of the function.

In passing, I removed unnecessary members in
check_ivm_restriction_context, and moved the check for OR and NOT
expression  was moved from  rewrite_exists_subquery_walker to
check_ivm_restriction_context.
---
 createas.c          | 105 ++++++++++++++++++++++++--------------------
 expected/pg_ivm.out |   9 ++--
 matview.c           |  42 +++++++-----------
 3 files changed, 79 insertions(+), 77 deletions(-)

diff --git a/createas.c b/createas.c
index 39f2807..e928023 100644
--- a/createas.c
+++ b/createas.c
@@ -65,14 +65,11 @@ typedef struct
 
 typedef struct
 {
-	bool	has_agg;
-	bool	has_sublinks;
-	bool	has_subquery;
-	bool    in_exists_subquery;	/* true, if it is in a exists subquery */
-	bool	in_jointree;		/* true, if it is in a join tree */
-	bool	is_simple_jointree;	/* true, if it is in a simple join tree or boolexpr directly under jointree */
-	List    *exists_qual_vars;
-	int		sublevels_up;
+	bool	has_agg;			/* the query has an aggregate? */
+	bool	allow_exists;		/* is EXISTS subquery allowed in the current node? */
+	bool    in_exists_subquery;	/* true, if under an EXISTS subquery */
+	List    *exists_qual_vars;	/* Vars used in EXISTS subqueries */
+	int		sublevels_up;		/* (current) nesting depth */
 } check_ivm_restriction_context;
 
 static void CreateIvmTriggersOnBaseTablesRecurse(Query *qry, Node *node, Oid matviewOid,
@@ -742,7 +739,13 @@ CreateIvmTrigger(Oid relOid, Oid viewOid, int16 type, int16 timing, bool ex_lock
 static void
 check_ivm_restriction(Node *node)
 {
-	check_ivm_restriction_context context = {false, false, false, false, false, false, NIL, 0};
+	check_ivm_restriction_context context;
+
+	context.has_agg = false;
+	context.allow_exists = false;
+	context.in_exists_subquery = false;
+	context.exists_qual_vars = NIL;
+	context.sublevels_up = 0;;
 
 	check_ivm_restriction_walker(node, &context);
 }
@@ -750,6 +753,10 @@ check_ivm_restriction(Node *node)
 static bool
 check_ivm_restriction_walker(Node *node, check_ivm_restriction_context *context)
 {
+	/* EXISTS is allowed only in this node */
+	bool allow_exists = context->allow_exists;
+	context->allow_exists = false;
+
 	if (node == NULL)
 		return false;
 
@@ -809,8 +816,6 @@ check_ivm_restriction_walker(Node *node, check_ivm_restriction_context *context)
 							(errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
 							 errmsg("recursive query is not supported on incrementally maintainable materialized view")));
 
-				context->has_sublinks |= qry->hasSubLinks;
-
 				/* system column restrictions */
 				vars = pull_vars_of_level((Node *) qry, 0);
 				foreach(lc, vars)
@@ -904,10 +909,8 @@ check_ivm_restriction_walker(Node *node, check_ivm_restriction_context *context)
 
 					if (rte->rtekind == RTE_SUBQUERY)
 					{
-						context->has_subquery = true;
-
 						context->sublevels_up++;
-						check_ivm_restriction_walker((Node *)rte->subquery, context);
+						check_ivm_restriction_walker((Node *) rte->subquery, context);
 						context->sublevels_up--;
 					}
 				}
@@ -997,38 +1000,17 @@ check_ivm_restriction_walker(Node *node, check_ivm_restriction_context *context)
 				expression_tree_walker(node, check_ivm_restriction_walker, (void *) context);
 				break;
 			}
-		case T_List:
+		case T_FromExpr:
 			{
-				ListCell   *temp;
-				foreach(temp, (List *) node)
-				{
-					check_ivm_restriction_walker(lfirst(temp), context);
-				}
-				break;
-			}
-                case T_FromExpr:
-                        {
-                                FromExpr   *from = (FromExpr *) node;
+				FromExpr   *from = (FromExpr *) node;
+
+				check_ivm_restriction_walker((Node *) from->fromlist, context);
 
-				check_ivm_restriction_walker((Node *)from->fromlist, context);
 				/*
-				 * check the sublink restrictions.
-				 * Currently, EXISTS subqueries with condition other than 'AND' is not supported.
+				 * EXIEST is allowed directly under FROM clause
 				 */
-				if (from->quals == NULL)
-					break;
-				if (context->has_sublinks && !context->in_exists_subquery &&
-					!IsA(from->quals, SubLink) && !IsA(from->quals, BoolExpr))
-					ereport(ERROR,
-							(errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
-							 errmsg("this query is not allowed on incrementally maintainable materialized view"),
-							 errhint("sublink only supports simple conditions with EXISTS clause in WHERE clause")));
-
-				context->in_jointree = true;
-				context->is_simple_jointree = true;
+				context->allow_exists = true;
 				check_ivm_restriction_walker(from->quals, context);
-				context->is_simple_jointree = false;
-				context->in_jointree = false;
 				break;
 			}
 		case T_JoinExpr:
@@ -1086,20 +1068,51 @@ check_ivm_restriction_walker(Node *node, check_ivm_restriction_context *context)
 		case T_BoolExpr:
 			{
 				BoolExpr *expr = (BoolExpr *) node;
-				expression_tree_walker((Node *) expr->args, check_ivm_restriction_walker, (void *) context);
+				BoolExprType type = ((BoolExpr *) node)->boolop;
+				ListCell *lc;
+
+				switch (type)
+				{
+					case AND_EXPR:
+						foreach(lc, expr->args)
+						{
+							Node *opnode = (Node *) lfirst(lc);
+
+							/*
+							 * EXIEST is allowed under AND expression only if it is
+							 * directly under WHERE.
+							 */
+							if (allow_exists)
+								context->allow_exists = true;
+							check_ivm_restriction_walker(opnode, context);
+						}
+						break;
+					case OR_EXPR:
+					case NOT_EXPR:
+						if (checkExprHasSubLink(node))
+							ereport(ERROR,
+									(errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
+									 errmsg("this query is not allowed on incrementally maintainable materialized view"),
+									 errhint("OR or NOT conditions and EXISTS condition can not be used together")));
+
+						expression_tree_walker((Node *) expr->args, check_ivm_restriction_walker, (void *) context);
+						break;
+				}
 				break;
 			}
 		case T_SubLink:
 			{
-				/* Currently, EXISTS clause is supported only */
 				Query *subselect;
 				SubLink	*sublink = (SubLink *) node;
-				if (!context->in_jointree || sublink->subLinkType != EXISTS_SUBLINK)
+
+				/* Only EXISTS clause is supported if it is directly under WHERE */
+				if (!allow_exists || sublink->subLinkType != EXISTS_SUBLINK)
 					ereport(ERROR,
 							(errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
 							 errmsg("this query is not allowed on incrementally maintainable materialized view"),
 							 errhint("sublink only supports subquery with EXISTS clause in WHERE clause")));
-				if (context->sublevels_up > 0 || (context->in_jointree && !context->is_simple_jointree))
+
+				if (context->sublevels_up > 0)
 					ereport(ERROR,
 							(errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
 							 errmsg("nested sublink is not supported on incrementally maintainable materialized view")));
@@ -1119,8 +1132,6 @@ check_ivm_restriction_walker(Node *node, check_ivm_restriction_context *context)
 				break;
 			}
 		default:
-			// not a simple query, if a condition don't match these
-			context->is_simple_jointree = false;
 			expressi [...]

2024-02-27 11:19 UTC, yugo-n commented
I copy and paste the patches here for making your review easier.

<details>

<summary>0001-Fix-check-for-EXISTS-subquery-support.patch</summary>

```diff
From 7e93cc1e176fbfda1d0cfe3bf4969988197dc680 Mon Sep 17 00:00:00 2001
From: Yugo Nagata <nagata@sraoss.co.jp>
Date: Tue, 27 Feb 2024 10:38:33 +0900
Subject: [PATCH 1/2] Fix check for EXISTS subquery support

Currently, EXISTS subquery is allowed only directly under WHERE
clause or in AND expression that is directly under WHERE.

In order to confirm this, I added a new boolean member
allow_context into check_ivm_restriction_context. This member
means whether EXISTS subquery is allowed in the current node being
examined in   check_ivm_restriction_walker. This should be set
just before calling check_ivm_restriction_walker for nodes directly
under WHERE or operands of AND expression direct under WHERE, and
is reset to false on every call of the function.

In passing, I removed unnecessary members in
check_ivm_restriction_context, and moved the check for OR and NOT
expression  was moved from  rewrite_exists_subquery_walker to
check_ivm_restriction_context.
---
 createas.c          | 105 ++++++++++++++++++++++++--------------------
 expected/pg_ivm.out |   9 ++--
 matview.c           |  42 +++++++-----------
 3 files changed, 79 insertions(+), 77 deletions(-)

diff --git a/createas.c b/createas.c
index 39f2807..e928023 100644
--- a/createas.c
+++ b/createas.c
@@ -65,14 +65,11 @@ typedef struct
 
 typedef struct
 {
-	bool	has_agg;
-	bool	has_sublinks;
-	bool	has_subquery;
-	bool    in_exists_subquery;	/* true, if it is in a exists subquery */
-	bool	in_jointree;		/* true, if it is in a join tree */
-	bool	is_simple_jointree;	/* true, if it is in a simple join tree or boolexpr directly under jointree */
-	List    *exists_qual_vars;
-	int		sublevels_up;
+	bool	has_agg;			/* the query has an aggregate? */
+	bool	allow_exists;		/* is EXISTS subquery allowed in the current node? */
+	bool    in_exists_subquery;	/* true, if under an EXISTS subquery */
+	List    *exists_qual_vars;	/* Vars used in EXISTS subqueries */
+	int		sublevels_up;		/* (current) nesting depth */
 } check_ivm_restriction_context;
 
 static void CreateIvmTriggersOnBaseTablesRecurse(Query *qry, Node *node, Oid matviewOid,
@@ -742,7 +739,13 @@ CreateIvmTrigger(Oid relOid, Oid viewOid, int16 type, int16 timing, bool ex_lock
 static void
 check_ivm_restriction(Node *node)
 {
-	check_ivm_restriction_context context = {false, false, false, false, false, false, NIL, 0};
+	check_ivm_restriction_context context;
+
+	context.has_agg = false;
+	context.allow_exists = false;
+	context.in_exists_subquery = false;
+	context.exists_qual_vars = NIL;
+	context.sublevels_up = 0;;
 
 	check_ivm_restriction_walker(node, &context);
 }
@@ -750,6 +753,10 @@ check_ivm_restriction(Node *node)
 static bool
 check_ivm_restriction_walker(Node *node, check_ivm_restriction_context *context)
 {
+	/* EXISTS is allowed only in this node */
+	bool allow_exists = context->allow_exists;
+	context->allow_exists = false;
+
 	if (node == NULL)
 		return false;
 
@@ -809,8 +816,6 @@ check_ivm_restriction_walker(Node *node, check_ivm_restriction_context *context)
 							(errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
 							 errmsg("recursive query is not supported on incrementally maintainable materialized view")));
 
-				context->has_sublinks |= qry->hasSubLinks;
-
 				/* system column restrictions */
 				vars = pull_vars_of_level((Node *) qry, 0);
 				foreach(lc, vars)
@@ -904,10 +909,8 @@ check_ivm_restriction_walker(Node *node, check_ivm_restriction_context *context)
 
 					if (rte->rtekind == RTE_SUBQUERY)
 					{
-						context->has_subquery = true;
-
 						context->sublevels_up++;
-						check_ivm_restriction_walker((Node *)rte->subquery, context);
+						check_ivm_restriction_walker((Node *) rte->subquery, context);
 						context->sublevels_up--;
 					}
 				}
@@ -997,38 +1000,17 @@ check_ivm_restriction_walker(Node *node, check_ivm_restriction_context *context)
 				expression_tree_walker(node, check_ivm_restriction_walker, (void *) context);
 				break;
 			}
-		case T_List:
+		case T_FromExpr:
 			{
-				ListCell   *temp;
-				foreach(temp, (List *) node)
-				{
-					check_ivm_restriction_walker(lfirst(temp), context);
-				}
-				break;
-			}
-                case T_FromExpr:
-                        {
-                                FromExpr   *from = (FromExpr *) node;
+				FromExpr   *from = (FromExpr *) node;
+
+				check_ivm_restriction_walker((Node *) from->fromlist, context);
 
-				check_ivm_restriction_walker((Node *)from->fromlist, context);
 				/*
-				 * check the sublink restrictions.
-				 * Currently, EXISTS subqueries with condition other than 'AND' is not supported.
+				 * EXIEST is allowed directly under FROM clause
 				 */
-				if (from->quals == NULL)
-					break;
-				if (context->has_sublinks && !context->in_exists_subquery &&
-					!IsA(from->quals, SubLink) && !IsA(from->quals, BoolExpr))
-					ereport(ERROR,
-							(errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
-							 errmsg("this query is not allowed on incrementally maintainable materialized view"),
-							 errhint("sublink only supports simple conditions with EXISTS clause in WHERE clause")));
-
-				context->in_jointree = true;
-				context->is_simple_jointree = true;
+				context->allow_exists = true;
 				check_ivm_restriction_walker(from->quals, context);
-				context->is_simple_jointree = false;
-				context->in_jointree = false;
 				break;
 			}
 		case T_JoinExpr:
@@ -1086,20 +1068,51 @@ check_ivm_restriction_walker(Node *node, check_ivm_restriction_context *context)
 		case T_BoolExpr:
 			{
 				BoolExpr *expr = (BoolExpr *) node;
-				expression_tree_walker((Node *) expr->args, check_ivm_restriction_walker, (void *) context);
+				BoolExprType type = ((BoolExpr *) node)->boolop;
+				ListCell *lc;
+
+				switch (type)
+				{
+					case AND_EXPR:
+						foreach(lc, expr->args)
+						{
+							Node *opnode = (Node *) lfirst(lc);
+
+							/*
+							 * EXIEST is allowed under AND expression only if it is
+							 * directly under WHERE.
+							 */
+							if (allow_exists)
+								context->allow_exists = true;
+							check_ivm_restriction_walker(opnode, context);
+						}
+						break;
+					case OR_EXPR:
+					case NOT_EXPR:
+						if (checkExprHasSubLink(node))
+							ereport(ERROR,
+									(errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
+									 errmsg("this query is not allowed on incrementally maintainable materialized view"),
+									 errhint("OR or NOT conditions and EXISTS condition can not be used together")));
+
+						expression_tree_walker((Node *) expr->args, check_ivm_restriction_walker, (void *) context);
+						break;
+				}
 				break;
 			}
 		case T_SubLink:
 			{
-				/* Currently, EXISTS clause is supported only */
 				Query *subselect;
 				SubLink	*sublink = (SubLink *) node;
-				if (!context->in_jointree || sublink->subLinkType != EXISTS_SUBLINK)
+
+				/* Only EXISTS clause is supported if it is directly under WHERE */
+				if (!allow_exists || sublink->subLinkType != EXISTS_SUBLINK)
 					ereport(ERROR,
 							(errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
 							 errmsg("this query is not allowed on incrementally maintainable materialized view"),
 							 errhint("sublink only supports subquery with EXISTS clause in WHERE clause")));
-				if (context->sublevels_up > 0 || (context->in_jointree && !context->is_simple_jointree))
+
+				if (context->sublevels_up > 0)
 					ereport(ERROR,
 							(errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
 							 errmsg("nested sublink is not supported on incrementally maintainable materialized view")));
@@ -1119,8 +1132,6 @@ check_ivm_restriction_walker(Node *node, check_ivm_restriction_context *context)
 				break;
 			}
 		default:
-			// not a simple query, if a condition don't match these
-			context->is_simple_jointree = false;
 			expression_tree_walker(node, check_ivm_restriction_walker, (void *) context);
 			 [...]

2024-03-01 08:15 UTC, thoshiai commented
Thanks for review and suggestion.
I apply your patches!

2024-03-01 08:24 UTC, yugo-n commented
Could you fix the conflict on the regression test?

2024-03-01 11:33 UTC, merged